import { useEffect, useRef } from 'react'
import { ArrowDown, X } from 'lucide-react'
import { motion } from 'framer-motion'
import { ProjectPreview } from '../sections/Work'
import { Reveal } from '../components/Motion'
import type { Project } from '../data/portfolio'
export default function ProjectCaseStudy({ project, onClose }: { project: Project; onClose: () => void }) {
 const dialog = useRef<HTMLDialogElement>(null)
 useEffect(() => { const previous = document.activeElement as HTMLElement; const el = dialog.current; el?.showModal(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = overflow; el?.close(); previous?.focus() } }, [])
 const sections = [ ['Overview', project.description], ['Problem / Goal', project.goal], ['Approach', '[Add the requirements, design choices and technical trade-offs you considered.]'], ['Technology', project.tags.join(' · ')], ['Development', '[Add your implementation details, contribution and technical challenges.]'], ['Deployment', project.kind === 'fitness' ? 'Docker and CI/CD were part of the project workflow. [Add the deployment platform and pipeline details.]' : '[Add the hosting platform and deployment workflow, if applicable.]'], ['What I Learned', '[Add your personal takeaways and what you would improve next.]'] ]
 return <dialog className="case-dialog" ref={dialog} onCancel={e => { e.preventDefault(); onClose() }} aria-labelledby="case-title"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}><header className="case-header"><span>SARTHAK<span className="lime">.</span> / PROJECT {project.id}</span><button className="button button-outline" onClick={onClose}>Close <X size={18} /></button></header><div className="case-body"><p className="eyebrow">{project.category}</p><h1 id="case-title">{project.name}</h1><p className="case-disclaimer">Illustrative concept preview, not an original project screenshot. Bracketed text marks details to add before publishing.</p><ProjectPreview kind={project.kind} /><div className="case-columns"><aside><p className="eyebrow">THE BUILD JOURNEY</p>{project.workflow.map((step, i) => <Reveal key={step} className="case-stage"><span>0{i + 1}</span>{step}<ArrowDown size={15} /></Reveal>)}</aside><div>{sections.map(([title, text], i) => <Reveal key={title} className="case-section"><p className="eyebrow">0{i + 1} — {title.toUpperCase()}</p><h2>{title}</h2><p className={text.startsWith('[') ? 'placeholder-copy' : ''}>{text}</p></Reveal>)}</div></div><button className="button button-primary" onClick={onClose}>Back to selected work <X size={16} /></button></div></motion.div></dialog>
}
