import { useRef, useState } from 'react'
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion'
import { ArrowLeft, ArrowRight, Check, Cpu, Sparkles } from 'lucide-react'
import { Reveal, SectionHeading } from '../components/Motion'
import { processSteps } from '../data/portfolio'

export default function Process() {
  const container = useRef<HTMLElement>(null)
  const reduced = useReducedMotion()
  const { scrollYProgress } = useScroll({ target: container, offset: ['start start', 'end end'] })
  const x = useTransform(scrollYProgress, [0, 1], ['0%', '-57.5%'])
  return <><section id="process" className="process-section" ref={container}><div className="process-sticky"><div className="section-shell"><SectionHeading eyebrow="HOW I BUILD" title="From idea to software." description="A considered process. No shortcuts on the things that matter." /><div className="process-viewport" tabIndex={0} role="region" aria-label="Seven development steps. Scroll horizontally on touch devices; use arrow keys when focused." onKeyDown={e => { if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { e.preventDefault(); if (window.matchMedia('(min-width: 901px)').matches && !reduced) window.scrollBy({ top: e.key === 'ArrowRight' ? 220 : -220, behavior: 'smooth' }); else e.currentTarget.scrollBy({ left: e.key === 'ArrowRight' ? 280 : -280, behavior: reduced ? 'instant' : 'smooth' }) } }}><motion.div className="process-track" style={{ x: reduced ? 0 : x }}>{processSteps.map((step, i) => <div className="process-card" key={step.title}><div className="process-number"><span>{step.icon}</span><ArrowRight size={20} /></div><div className="process-connector"><span /></div><h3>{step.title}<span>.</span></h3><p>{step.text}</p><span className="step-meta">STEP {step.icon} / 07 {i === 6 && <Check size={13} />}</span></div>)}</motion.div></div><div className="process-footer"><span><ArrowLeft size={13} /> SCROLL TO FOLLOW THE PROCESS <ArrowRight size={13} /></span><div><motion.span style={{ scaleX: scrollYProgress }} /></div></div></div></div></section><AiDirection /></>
}
const aiStages = [
  { title: 'Idea', detail: 'Begin with a real problem and a clear idea of who the software is for.' },
  { title: 'AI-assisted exploration', detail: 'Explore possibilities, challenge assumptions and consider different approaches with AI assistance.' },
  { title: 'Architecture', detail: 'Keep engineering judgment at the center: choose sensible boundaries, data flows and tools.' },
  { title: 'Prototype', detail: 'Use rapid prototyping to make an idea tangible and test the experience early.' },
  { title: 'Engineering', detail: 'Review, understand and refine the implementation rather than blindly accepting generated code.' },
  { title: 'Testing', detail: 'Validate functionality, accessibility and the assumptions behind the solution.' },
  { title: 'Deployment', detail: 'Prepare the application for use, then learn from feedback and keep improving.' },
]
function AiDirection() {
  const [stage, setStage] = useState(0)
  return <section className="section-shell section-pad"><Reveal className="ai-panel"><div className="ai-intro"><p className="eyebrow"><Sparkles size={14} /> THE NEXT CHAPTER</p><h2>Building software<br />in the <span>AI era.</span></h2><p>AI-assisted development is changing how software is designed and built. I am exploring how AI can accelerate prototyping, development, debugging, documentation and product experimentation while keeping engineering judgment at the center.</p><span className="ai-principle"><span className="status-dot" /> AI accelerates the process.<br />Engineering decisions still matter.</span></div><div className="ai-workflow"><div className="ai-workflow-heading"><Cpu size={17} /><span>HUMAN THINKING. AI ASSISTANCE.</span><span className="exploring-label">EXPLORING</span></div><div className="ai-stages" role="tablist" aria-label="AI-assisted development workflow">{aiStages.map((s, i) => <button key={s.title} id={`ai-tab-${i}`} role="tab" aria-selected={stage === i} aria-controls="ai-stage-panel" tabIndex={stage === i ? 0 : -1} onClick={() => setStage(i)} onKeyDown={e => { if (['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? aiStages.length - 1 : (i + (e.key === 'ArrowDown' ? 1 : -1) + aiStages.length) % aiStages.length; setStage(next); document.getElementById(`ai-tab-${next}`)?.focus() } }}><span>0{i + 1}</span>{s.title}<ArrowRight size={14} /></button>)}</div><div id="ai-stage-panel" role="tabpanel" aria-labelledby={`ai-tab-${stage}`} tabIndex={0} className="ai-detail">{aiStages[stage].detail}</div></div></Reveal><div className="thinking-section"><SectionHeading eyebrow="HOW I THINK ABOUT SOFTWARE" title="Good software starts with intention." /><div className="thinking-grid">{[{ t: 'Understand the problem', d: 'The right question comes before the first line of code.' }, { t: 'Build practically', d: 'Useful, clear and maintainable beats unnecessarily complex.' }, { t: 'Use AI intelligently', d: 'A tool for exploration and momentum, not a substitute for judgment.' }, { t: 'Iterate and improve', d: 'Keep learning from feedback and make the next version better.' }].map((c, i) => <Reveal key={c.t} delay={i * 0.05}><span className="thinking-number">0{i + 1}</span><h3>{c.t}</h3><p>{c.d}</p></Reveal>)}</div></div></section>
}
